#!/bin/bash
if ./gradlew generateColorizeLexer; then 
	echo "generating parser..."
else
	exit 1
fi
if ./gradlew generateParser; then
	echo "compiling typescript..."
else
	exit 1
fi
touch ./src/main-generated/javascript/TextTemplateInterpreter.js # fix wierd tsc ordering issue	
if tsc; then
	echo "running webpack..."
else
	exit 1
fi
npx webpack
echo "starting server ... (http://localhost:3000)"
npm start