#!/bin/bash
if ./gradlew generateParser; then
	echo "compiling typescript..."
else
	exit 1
fi
if tsc --sourceMap; then
	echo "running webpack..."
else
	exit 1
fi
webpack
echo "starting server ... (http://localhost:3000)"
npm start